updated template and CI

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -10,42 +10,82 @@ stages:
   - test
   - release
 
+build:
+  stage: build
+  image: node:24-slim
+  rules:
+    - changes:
+        compare_to: 'refs/heads/main'
+        paths:
+          - 'src/**'
+  before_script:
+    - git config --local user.email "github-actions[bot]@users.noreply.github.com"
+    - git config --local user.name "github-actions[bot]"
+    - git remote add origin "https://$CI_SERVER_HOST/$CI_PROJECT_PATH/"
+  script:
+    - npm ci
+    - npm run build
+    - |
+      if git diff --quiet; then
+        echo "no change after build"
+      else
+        git add .
+        git commit -m "updated by CI build"
+        git push origin main
+      fi
+
+# include the local convert-weblate-csv template and pass inputs to create a test job
 include:
-  # include the local convert-weblate-csv template and pass inputs to create a test job
   - local: templates/convert-weblate-csv.yml
+    rules:
+      - changes:
+          compare_to: 'refs/heads/main'
+          paths:
+            - dist/**
+            - src/**
+            - test/**
+            - .gitlab-ci.yml
     inputs:
-      job_name: convert-weblate-csv
       stage: test
+      job_name: convert-single-original-to-weblate
       artifacts: test/single/weblate/*
       invert: false
       multi: false
       input: test/single/original/localization_ja.csv
       output: test/single/weblate/localization_ja.csv
+      stats_file: test/single/weblate/stats.txt
       columns: context,source,target,developer_comments
-      obsolete: true
       header: true
+      encoding: utf8
+      utf_bom: false
+      crlf: CRLF
+      separator: ","
+      obsolete: true
+      quoting: false
 
-verify-conversion:
+verify-conversion-single-original-to-weblate:
   stage: test
   image: alpine:latest
   needs:
-    - job: convert-weblate-csv
+    - job: convert-single-original-to-weblate
       artifacts: true
   rules:
-    - when: always
+    - when: on_success
   script:
     - apk add --no-cache diffutils
-    - echo "Comparing expected vs produced files"
-    - if [ ! -f test/single/weblate/localization_ja.csv ]; then echo "Produced file not found" && exit 2; fi
-    - if [ ! -f test/single/weblate/localization_ja_expected.csv ]; then echo "Expected file not found" && exit 2; fi
-    - diff -u test/single/weblate/localization_ja_expected.csv test/single/weblate/localization_ja.csv || (echo "Conversion mismatch" && exit 1)
+    - echo "Comparing expected vs produced CSVs"
+    - if [ ! -f test/single/weblate/localization_ja.csv ]; then echo "Produced CSV not found" && exit 2; fi
+    - diff -u test/single/weblate/localization_ja_expected.csv test/single/weblate/localization_ja.csv || (echo "CSV conversion mismatch" && exit 1)
+    - echo "Comparing expected vs produced stats"
+    - if [ ! -f test/single/weblate/stats.txt ]; then echo "Produced stats not found" && exit 2; fi
+    - diff -u test/single/weblate/stats_expected.txt test/single/weblate/stats.txt || (echo "Stats conversion mismatch" && exit 1)
 
-# create-release:
-#   stage: release
-#   image: registry.gitlab.com/gitlab-org/release-cli:latest
-#   rules:
-#     - if: $CI_COMMIT_TAG
-#   script: echo "Creating release $CI_COMMIT_TAG"
-#   release:
-#     tag_name: $CI_COMMIT_TAG
-#     description: "Release $CI_COMMIT_TAG of components repository $CI_PROJECT_PATH"
+create-release:
+  stage: release
+  image: registry.gitlab.com/gitlab-org/release-cli:latest
+  rules:
+    - if: $CI_COMMIT_TAG
+  script: echo "Creating release $CI_COMMIT_TAG"
+  release:
+    tag_name: $CI_COMMIT_TAG
+    description: "Release $CI_COMMIT_TAG of components repository $CI_PROJECT_PATH"
